kind: pipeline
type: docker
name: deploy-snapx-admin

trigger: 
  event:
    - push
    - tag

steps:
  - name: build-stage
    image: node:16.19-alpine
    when:
      branch:
        - dev
      event:
        - push
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
    commands:
      - npm config set registry https://registry.npm.taobao.org
      - npm install
      - npm run build:stage -- --base=/admin
  
  - name: deploy-stage
    image: appleboy/drone-scp
    when:
      branch:
        - dev
      event:
        - push
    depends_on:
      - build-stage
    settings:
      host: 54.251.186.82
      port: 22
      username: app
      key:
        from_secret: 'ssh_key'
      source: /drone/src/dist/
      target: /app/srv/public/snapx-admin/
  
  - name: post-deploy-stage
    image: 'appleboy/drone-ssh'
    when:
      branch:
        - dev
      event:
        - push
    depends_on:
      - build-stage
      - deploy-stage
    settings:
      host: 54.251.186.82
      port: 22
      username: app
      key:
        from_secret: 'ssh_key'
      script:
        - cd /app/srv/public/snapx-admin/
        - rm -r `ls . |grep -v drone`
        - mv ./drone/src/dist/* .
        - rm -r ./drone

  - name: build-prod
    image: node:16.19-alpine
    when:
      event:
        - tag
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
    commands:
      - npm config set registry https://registry.npm.taobao.org
      - npm install
      - npm run build:prod -- --base=/admin

  - name: deploy-prod
    image: appleboy/drone-scp
    when:
      event:
        - tag
    depends_on:
      - build-prod
    settings:
      host: 54.169.146.166
      port: 22
      username: app
      key:
        from_secret: 'ssh_key_prod'
      source: /drone/src/dist/
      target: /app/srv/public/snapx-admin/
  
  - name: post-deploy-prod
    image: 'appleboy/drone-ssh'
    when:
      event:
        - tag
    depends_on:
      - build-prod
      - deploy-prod
    settings:
      host: 54.169.146.166
      port: 22
      username: app
      key:
        from_secret: 'ssh_key_prod'
      script:
        - cd /app/srv/public/snapx-admin/
        - rm -r `ls . |grep -v drone`
        - mv ./drone/src/dist/* .
        - rm -rf ./drone

volumes:
  - name: node_modules
    host:
      path: /app/var/drone/node/node_modules
  - name: deploy-dir
    host:
      path: /app/srv/public/snapx-admin